### ISSUE TITLE
Why are fine-grained tokens (beta) required?

### ISSUE THREAD

**Issue by Aariq** [resbazaz/website#103]
I use GitHub with https and a PAT, but this repo requires one of the new fine-grained tokens and doesn't work with a "classic" token.  I'm curious why and if that requirement might be relaxed?

**Comment by julianpistorius** [comment]
Good question. I don't know. I changed this in the organization settings so you should be able to use a classic PAT now. Let me know if it works.

@alex-r-bigelow do you remember if there was a reason we set the personal access token settings to prevent this (assuming we did set it)?

**Comment by alex-r-bigelow** [comment]
I don't remember changing anything w.r.t. personal access tokens; classic PATs should be fine...

I vaguely remember that we updated a few different permissions-related constraints back when we were messing around with Github's GraphQL endpoint, but I doubt that would be relevant to PATs.

**Comment by julianpistorius** [comment]
Requirement relaxed. Closing as completed. Re-open if you still have problems @Aariq.
