### ISSUE TITLE
Make it more clear that this is the repo for the *website*

### ISSUE THREAD

**Issue by Aariq** [resbazaz/website#47]
The README, CONTRIBUTING, and issues in this repo seem directed toward resBazAZ the organization as a whole, but the *code* in this repo is to build the website.  Suggestions:

- [x] rename this repo something like `resbaz-website`
- [x] create and pin a `resbazaz/resbazaz` repo to hold organization level stuff
- [x] move Global Sprint issues to resbazaz repo
- [ ] move appropriate parts of README and CONTRIBUTING, code_of_conduct, etc. to `resbazaz` repo
- [ ] edit README and CONTRIBUTING in this repo to focus on instructions on how to build and edit the jekyll site.

Just some ideas from a naive newcomer's perspective.

**Comment by julianpistorius** [comment]
@Aariq I renamed the repo to `website`.

**Comment by julianpistorius** [comment]
FYI this repository is no longer a fork of the [Mozilla Study Group repo](https://github.com/mozillascience/studyGroup)! 

Thanks to GitHub support for helping decouple.
